name: dynamics
channels:
  - conda-forge
  - defaults
dependencies:
  - brotlipy=0.7.0
  - ca-certificates=2025.2.25
  - certifi=2025.4.26
  - cffi=1.17.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - conda=23.7.2
  - conda-content-trust=0.1.1
  - conda-package-handling=1.8.1
  - console_shortcut=0.1.1
  - cryptography=37.0.1
  - idna=3.7
  - jupyter
  - jupyterlab=3.4.3
  - matplotlib=3.9.2
  - nodejs=18.6.0
  - notebook=6.4.11
  - numpy=1.26.4
  - openssl=1.1.1w
  - pip=25.1
  - plotly=6.0.1
  - pycosat=0.6.6
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.9.12
  - requests=2.32.3
  - ruamel_yaml=0.17.21
  - scipy=1.13.1
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.45.3
  - tqdm=4.67.1
  - tzdata=2025b
  - urllib3=2.3.0
  - wheel=0.45.1
  - xarray=2023.6.0
  - yaml=0.2.5